from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DokanAssets:


	# Click Rule Assets
	# 道馆突破排名弹出时,点击此区域关闭
	C_DOKAN_TOPPA_RANK_CLOSE_AREA = RuleClick(roi_front=(1150,380,100,150), roi_back=(1150,380,100,150), name="dokan_toppa_rank_close_area")
	# 查找道馆时 点击此区域 隐藏道馆详情(显示防守人数,馆主等级等的卡片)
	C_DOKAN_CANCEL_SELECT_DOKAN = RuleClick(roi_front=(1070,610,30,90), roi_back=(1070,610,30,90), name="dokan_cancel_select_dokan")
	# ruleanimate 用作检测选择道馆时,确定地图区域稳定无动作
	C_DOKAN_CANCEL_SELECT_DOKAN_CHECK_ANIMATE = RuleClick(roi_front=(600,330,80,60), roi_back=(600,330,80,60), name="dokan_cancel_select_dokan_check_animate")
	# 查找道馆时 刷新道馆列表
	C_DOKAN_REFRESH = RuleClick(roi_front=(1140,630,40,30), roi_back=(1140,630,40,30), name="dokan_refresh")
	# 道馆战斗时,左上角 退出按钮区域
	C_DOKAN_BATTLE_QUIT_AREA = RuleClick(roi_front=(10,36,50,14), roi_back=(10,36,50,14), name="dokan_battle_quit_area")


	# Image Rule Assets
	# 是否已经成功进入道馆，上面中间的“道馆突破”文字
	I_RYOU_DOKAN_CHECK = RuleImage(roi_front=(567,15,144,42), roi_back=(567,15,144,42), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_check.png")
	# 道馆内式神录
	I_RYOU_DOKAN_SHIKIGAMI = RuleImage(roi_front=(995,602,77,72), roi_back=(960,580,140,120), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_shikigami.png")
	# 优先攻击选项
	I_RYOU_DOKAN_ATTACK_PRIORITY = RuleImage(roi_front=(767,663,48,27), roi_back=(520,660,557,48), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_priority.png")
	# 优先攻击: 见习
	I_RYOU_DOKAN_ATTACK_PRIORITY_0 = RuleImage(roi_front=(98,170,94,43), roi_back=(98,170,94,43), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_priority_0.png")
	# 优先攻击: 初级
	I_RYOU_DOKAN_ATTACK_PRIORITY_1 = RuleImage(roi_front=(342,175,96,42), roi_back=(342,175,96,42), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_priority_1.png")
	# 优先攻击: 中级
	I_RYOU_DOKAN_ATTACK_PRIORITY_2 = RuleImage(roi_front=(585,175,89,35), roi_back=(585,175,89,35), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_priority_2.png")
	# 优先攻击: 高级
	I_RYOU_DOKAN_ATTACK_PRIORITY_3 = RuleImage(roi_front=(830,175,88,41), roi_back=(830,175,88,41), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_priority_3.png")
	# 优先攻击: 黑脸
	I_RYOU_DOKAN_ATTACK_PRIORITY_4 = RuleImage(roi_front=(1072,178,94,39), roi_back=(1072,178,94,39), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_priority_4.png")
	# 正在查找道馆,还未选择
	I_RYOU_DOKAN_FINDING_DOKAN = RuleImage(roi_front=(980,60,100,160), roi_back=(980,60,100,160), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_finding_dokan.png")
	# 已选择道馆
	I_RYOU_DOKAN_FOUND_DOKAN = RuleImage(roi_front=(440,580,360,140), roi_back=(440,580,360,140), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_found_dokan.png")
	# 状态：集结等待中。检查右下角的挑战是不是灰色的。FIXME 黄色和灰色的挑战截图总是傻傻分不清，先改用OCR
	I_RYOU_DOKAN_GATHERING = RuleImage(roi_front=(653,76,46,26), roi_back=(653,76,46,26), threshold=0.85, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_gathering.png")
	# 状态：检查右下角有没有挑战？通常是失败了，并退出来到集结界面，可重新开始点击右下角挑战进入战斗
	I_RYOU_DOKAN_START_CHALLENGE = RuleImage(roi_front=(1100,550,180,80), roi_back=(1100,550,180,80), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_start_challenge.png")
	# 状态：达到失败次数，CD中。观战按钮
	I_RYOU_DOKAN_CD = RuleImage(roi_front=(1122,566,117,74), roi_back=(1122,566,117,74), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_cd.png")
	# 馆主战等待中
	I_DOKAN_BOSS_WAITING = RuleImage(roi_front=(460,140,370,80), roi_back=(460,140,370,80), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_dokan_boss_waiting.png")
	# 馆主战 等待 或 进行中时 在寮境中出现的馆主图标
	I_RYOU_DOKAN_MASTER_BATTLE = RuleImage(roi_front=(862,69,41,89), roi_back=(640,0,640,360), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_master_battle.png")
	# 放弃突破
	I_DOKAN_ABANDONED_TOPPA = RuleImage(roi_front=(0,550,180,170), roi_back=(0,550,180,170), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_abandoned_toppa.png")
	# 馆主阶段右下角的放弃突破按钮
	I_DOKAN_ABANDONED_TOPPA_RIGHT = RuleImage(roi_front=(1100,600,106,53), roi_back=(900,500,380,220), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_abandoned_toppa.png")
	# 放弃突破 确认按钮
	I_DOKAN_ABANDONED_TOPPA_ENSURE = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_abandoned_toppa_ensure.png")
	# 放弃突破
	I_DOKAN_ABANDONED_TOPPA_TITLE = RuleImage(roi_front=(1020,160,260,80), roi_back=(1020,160,260,80), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_abandoned_toppa_title.png")
	# 状态：道馆胜利
	I_RYOU_DOKAN_WIN = RuleImage(roi_front=(422,49,100,80), roi_back=(348,13,319,178), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_win.png")
	# 馆主战,第一阵容
	I_RYOU_DOKAN_BATTLE_MASTER_FIRST = RuleImage(roi_front=(1113,205,50,28), roi_back=(1080,180,160,70), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_battle_master_first.png")
	# 馆主战,第二阵容
	I_RYOU_DOKAN_BATTLE_MASTER_SECOND = RuleImage(roi_front=(1114,208,48,25), roi_back=(1080,180,160,70), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_battle_master_second.png")
	# 状态：战斗结算，可能是打完小朋友了，也可能是失败了。
	I_RYOU_DOKAN_BATTLE_OVER = RuleImage(roi_front=(571,503,106,49), roi_back=(571,503,106,49), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_battle_over.png")
	# 道馆失败/成功 出现的突破排名 弹窗
	I_RYOU_DOKAN_TOPPA_RANK = RuleImage(roi_front=(110,80,170,70), roi_back=(110,80,170,70), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_toppa_rank.png")
	# 状态：道馆挑战失败，投票 保留赏金
	I_RYOU_DOKAN_FAILED_VOTE_KEEP_BOUNTY = RuleImage(roi_front=(1020,220,260,120), roi_back=(1020,220,260,120), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_failed_vote_keep_bounty.png")
	# 状态：道馆挑战失败，投票 再战道馆
	I_RYOU_DOKAN_FAILED_VOTE_BATTLE_AGAIN = RuleImage(roi_front=(1020,220,260,120), roi_back=(1020,220,260,120), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_failed_vote_battle_again.png")
	# 状态：道馆投票 放弃突破
	I_RYOU_DOKAN_ABANDONED_TOPPA_ABANDONED = RuleImage(roi_front=(1020,220,260,120), roi_back=(1020,220,260,120), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_abandoned_toppa_abandoned.png")
	# 道馆战斗界面 点击退出按钮后 弹出的确认按钮
	I_RYOU_DOKAN_QUIT_BATTLE_ENSURE = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_quit_battle_ensure.png")
	# 道馆退出确认
	I_RYOU_DOKAN_EXIT_ENSURE = RuleImage(roi_front=(678,395,125,56), roi_back=(678,395,125,56), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_exit_ensure.png")
	# 场景检测：神社
	I_SCENE_SHENSHE = RuleImage(roi_front=(477,165,63,65), roi_back=(477,165,65,80), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/scene_shenshe.png")
	# 道馆地图：可点击的建立道馆按钮，识别后需区分颜色
	I_RYOU_DOKAN_CREATE_DOKAN = RuleImage(roi_front=(240,600,94,90), roi_back=(240,600,94,90), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_create_dokan.png")
	# 道馆 地图界面 点击建立道馆按钮后弹窗中的 确认按钮
	I_RYOU_DOKAN_CREATE_DOKAN_ENSURE = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_create_dokan_ensure.png")
	# 道馆信息 右上角关闭按钮
	I_RYOU_DOKAN_DOKAN_INFO_CLOSE = RuleImage(roi_front=(1150,80,100,90), roi_back=(1150,80,100,90), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_dokan_info_close.png")
	# 寮境界面,道馆打完后 出现在底部的'今日可挑战机会'字样
	I_RYOU_DOKAN_TODAY_ATTACK_COUNT = RuleImage(roi_front=(500,630,250,50), roi_back=(500,630,250,50), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_today_attack_count.png")
	# 今日道馆已挑战成功
	I_RYOU_DOKAN_REMAIN_ATTACK_COUNT_DONE = RuleImage(roi_front=(550,610,220,80), roi_back=(550,610,220,80), threshold=0.9, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_remain_attack_count_done.png")
	# 今日可挑战次数:0次
	I_RYOU_DOKAN_REMAIN_ATTACK_COUNT_ZERO = RuleImage(roi_front=(650,610,110,80), roi_back=(650,610,110,80), threshold=0.9, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_remain_attack_count_zero.png")
	# 今日可挑战次数:1次
	I_RYOU_DOKAN_REMAIN_ATTACK_COUNT_ONE = RuleImage(roi_front=(650,610,110,80), roi_back=(650,610,110,80), threshold=0.9, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_remain_attack_count_one.png")
	# 今日可挑战次数:2次
	I_RYOU_DOKAN_REMAIN_ATTACK_COUNT_TWO = RuleImage(roi_front=(650,610,110,80), roi_back=(650,610,110,80), threshold=0.9, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_remain_attack_count_two.png")
	# 查找道馆时,中间防守人数字样,为了定位该图下方的 防守人数数字
	I_CENTER_POINT_PEOPLE_NUMBER = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_center_point_people_number.png")
	# 查找道馆时,挑战按钮
	I_CENTER_CHALLENGE = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_center_challenge.png")
	# 查找道馆时,确认挑战按钮
	I_CHALLENGE_ENSURE = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_challenge_ensure.png")
	# 查找道馆时,确认刷新道馆列表按钮
	I_REFRESH_ENSURE = RuleImage(roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_refresh_ensure.png")
	# 查找道馆时，右侧列表福利寮的鑫字徽章
	I_RIGHTPAD_XIN_ICON = RuleImage(roi_front=(1143,366,33,38), roi_back=(1110,20,110,610), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_rightpad_xin_icon.png")
	# 查找道馆时,右侧道馆赏金图标,为了定位该图右侧的 赏金金额
	I_RIGHTPAD_POINT_BOUNTY = RuleImage(roi_front=(1125,103,27,29), roi_back=(1077,0,171,602), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_rightpad_point_bounty.png")
	# 寮境中上部的标志
	I_RYOU_DOKAN_CENTER_TOP = RuleImage(roi_front=(500,20,300,70), roi_back=(500,20,300,70), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_center_top.png")
	# 左上角退出按钮-
	I_RYOU_DOKAN_DOKAN_QUIT = RuleImage(roi_front=(0,2,80,80), roi_back=(0,2,80,80), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_dokan_quit.png")
	# 道馆地图：灰色建立道馆按钮，表示己方道馆已建立，需区分颜色
	I_RYOU_DOKAN_HAVE_DOKAN = RuleImage(roi_front=(240,600,94,90), roi_back=(240,600,94,90), threshold=0.8, method="Template matching", file="./tasks/ZombieGuild/res/res_ryou_dokan_have_dokan.png")


	# Ocr Rule Assets
	# 道馆地图里找文字：万
	O_DOKAN_MAP = RuleOcr(roi=(270,130,740,460), area=(270,130,740,460), mode="Full", method="Default", keyword="万", name="dokan_map")
	# 查找道馆时,中间卡片上防守人数
	O_DOKAN_CENTER_PEOPLE_NUMBER = RuleOcr(roi=(0,0,0,0), area=(0,0,0,0), mode="Full", method="Default", keyword="", name="dokan_center_people_number")


	# Swipe Rule Assets
	# 道馆选择界面 右侧侧边栏 手指向上滑动
	S_DOKAN_LIST_UP = RuleSwipe(roi_front=(1100,420,30,21), roi_back=(1240,240,30,21), mode="default", name="dokan_list_up")
